

--By Chris M. Perez Santiago , 2016/10/10


{-
 Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
-}


fibonacci :: [Int]
fibonacci = serie'
    where serie' =1:1: zipWith (+) fibonacci(tail fibonacci)


filter_even_terms :: [Int]
filter_even_terms = filter(even) $ takeWhile (< 4000000) fibonacci

sums :: Int
sums = sum(filter_even_terms)

main = do
    print (sums)
